services:
  retrieval-app:
    build:
      context: ../../../
      dockerfile: Dockerfile
    image: openai/chatgpt-retrieval-plugin
    ports:
      - "8080:8080"
    depends_on:
      - qdrant
    environment:
      DATASTORE: "qdrant"
      QDRANT_URL: "http://qdrant"
      BEARER_TOKEN: "${BEARER_TOKEN}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
  qdrant:
    image: qdrant/qdrant:v1.3.0
    ports:
      - "6333:6333"
      - "6334:6334"